name: golang-pipeline-demo
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test
  push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        needs: test
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v2
            -
                name: What
                run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME}}
                    password: ${{secrets.DOCKER_ACCESS_TOKEN}}
            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    push: true
                    tags: muthonig/golang-pipeline:v1.0.0.2
#                     build-args: |
#                         BRANCH=${{ env.BRANCH }}
